Try running just 2 platforms on sauce

diff --git a/.github/workflows/continuous.yaml b/.github/workflows/continuous.yaml
--- a/.github/workflows/continuous.yaml
+++ b/.github/workflows/continuous.yaml
@@ -289,93 +289,93 @@ jobs:
 #        run: gsutil cp /home/runner/selenium-readersuite-local.txt gs://${{secrets.GCS_BUILD_UPLOAD_BUCKET}}/${{env.BUILD_RESULT_SUBDIR}}/selenium-readersuite-local.txt
 #        if: ${{ always() }}
 
-  selenium-allsuites-local:
-    # Start off with local firefox
-    name: "Selenium: Local"   # This name is referenced when slacking status
-    needs: sandbox-ready
-    runs-on: ubuntu-latest
-    services: 
-      selenium:
-        image: selenium/standalone-chrome:3.141.59
-        ports: [ "4444:4444" ]
-        volumes: ["/dev/shm:/dev/shm"]
-    steps:
-
-      # BEGIN SETUP
-      - name: Checkout Code
-        uses: actions/checkout@v2
-      - name: Set Up Python 3
-        uses: actions/setup-python@v1
-        with: 
-          python-version: '3.7'  
-
-      # Set Up Connection to Dev Mongo
-      # 1. Auth to cluster
-      # 2. Open encrypted connection
-      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
-        with:
-          service_account_key: ${{ secrets.DEV_CLOUDBUILD_SA_KEY }}
-          project_id: ${{ secrets.DEV_PROJECT }}
-
-      - name: Authenticate GHA Runner To Target Cluster
-        run: gcloud container clusters get-credentials ${{secrets.DEV_GKE_CLUSTER}} --zone ${{secrets.DEV_GKE_REGION}} --project ${{secrets.DEV_GCP_PROJECT}}
-
-      - name: Establish MongoDB Connection
-        run: kubectl port-forward svc/mongo 27017:27017 &
-      
-      - name: Await MongoDB Connection
-        run: sleep 20
-
-      - name: Confirm MongoDB Connection
-        # The following command returns a success code if mongo is available,
-        # and a failure code if it is not
-        run: curl localhost:27017
-
-      - name: Establish PostgreSQL Connection
-        run: kubectl port-forward svc/postgres 5432:5432 &
-
-      - name: Await MongoDB Connection
-        run: sleep 20
-
-      - name: Confirm PostgreSQL Connection
-        # if the PostgreSQL server is available, curl will fail with a '52' exit code
-        # if it is NOT available, it will fail with a '7' exit code
-        # run: curl localhost:5432; if [ $? -eq "52" ]; then exit 0; else exit 1; fi
-        run: exitCode=$(curl localhost:5432; echo $?); if [ $exitCode -eq 52 ]; then exit 0; else exit 1; fi
-
-      - name: Define GITHUB_SHA_SHORT
-        run: echo "GITHUB_SHA_SHORT=${GITHUB_SHA:0:6}" >> $GITHUB_ENV
-
-      # END SETUP
-      - name: Install Python Packages
-        run: pip3 install -r ./requirements.txt
-
-      - name: Run PageLoad Suite
-        run: python3 ./reader/browsertest/run_local_sel.py  | tee /home/runner/selenium-allsuites-local.txt # --parallel ; echo $?
-        shell: bash
-        env:
-          CI_RUN: "true"
-          CI_URL: https://${{env.GITHUB_SHA_SHORT}}.cauldron.sefaria.org
-          LOCAL_SELENIUM_URL: "http://localhost:4444/wd/hub"
-          SEFARIA_TEST_PASS: ${{ secrets.SEFARIA_APP_PASS }}
-          SEFARIA_TEST_USER: ${{ secrets.SEFARIA_APP_USER }}
-          PYTHONPATH: "."
-          DJANGO_SETTINGS_MODULE: sefaria.settings
-
-      - name: Authenticate GHA Runner to GCP
-        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
-        with:
-          service_account_key: ${{ secrets.GCS_BUILD_UPLOAD_KEY }}
-          project_id: ${{ secrets.BUILD_UPLOAD_PROJECT }}
-        if: ${{ always() }}
-
-      - name: Define BUILD_RESULT_SUBDIR
-        run: echo "BUILD_RESULT_SUBDIR=${GITHUB_SHA:0:8}" >> $GITHUB_ENV
-        if: ${{ always() }}
-
-      - name: Upload Build Results
-        run: gsutil cp /home/runner/selenium-allsuites-local.txt gs://${{secrets.GCS_BUILD_UPLOAD_BUCKET}}/${{env.BUILD_RESULT_SUBDIR}}/selenium-allsuites-local.txt
-        if: ${{ always() }}
+#  selenium-allsuites-local:
+#    # Start off with local firefox
+#    name: "Selenium: Local"   # This name is referenced when slacking status
+#    needs: sandbox-ready
+#    runs-on: ubuntu-latest
+#    services:
+#      selenium:
+#        image: selenium/standalone-chrome:3.141.59
+#        ports: [ "4444:4444" ]
+#        volumes: ["/dev/shm:/dev/shm"]
+#    steps:
+#
+#      # BEGIN SETUP
+#      - name: Checkout Code
+#        uses: actions/checkout@v2
+#      - name: Set Up Python 3
+#        uses: actions/setup-python@v1
+#        with:
+#          python-version: '3.7'
+#
+#      # Set Up Connection to Dev Mongo
+#      # 1. Auth to cluster
+#      # 2. Open encrypted connection
+#      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
+#        with:
+#          service_account_key: ${{ secrets.DEV_CLOUDBUILD_SA_KEY }}
+#          project_id: ${{ secrets.DEV_PROJECT }}
+#
+#      - name: Authenticate GHA Runner To Target Cluster
+#        run: gcloud container clusters get-credentials ${{secrets.DEV_GKE_CLUSTER}} --zone ${{secrets.DEV_GKE_REGION}} --project ${{secrets.DEV_GCP_PROJECT}}
+#
+#      - name: Establish MongoDB Connection
+#        run: kubectl port-forward svc/mongo 27017:27017 &
+#
+#      - name: Await MongoDB Connection
+#        run: sleep 20
+#
+#      - name: Confirm MongoDB Connection
+#        # The following command returns a success code if mongo is available,
+#        # and a failure code if it is not
+#        run: curl localhost:27017
+#
+#      - name: Establish PostgreSQL Connection
+#        run: kubectl port-forward svc/postgres 5432:5432 &
+#
+#      - name: Await MongoDB Connection
+#        run: sleep 20
+#
+#      - name: Confirm PostgreSQL Connection
+#        # if the PostgreSQL server is available, curl will fail with a '52' exit code
+#        # if it is NOT available, it will fail with a '7' exit code
+#        # run: curl localhost:5432; if [ $? -eq "52" ]; then exit 0; else exit 1; fi
+#        run: exitCode=$(curl localhost:5432; echo $?); if [ $exitCode -eq 52 ]; then exit 0; else exit 1; fi
+#
+#      - name: Define GITHUB_SHA_SHORT
+#        run: echo "GITHUB_SHA_SHORT=${GITHUB_SHA:0:6}" >> $GITHUB_ENV
+#
+#      # END SETUP
+#      - name: Install Python Packages
+#        run: pip3 install -r ./requirements.txt
+#
+#      - name: Run PageLoad Suite
+#        run: python3 ./reader/browsertest/run_local_sel.py  | tee /home/runner/selenium-allsuites-local.txt # --parallel ; echo $?
+#        shell: bash
+#        env:
+#          CI_RUN: "true"
+#          CI_URL: https://${{env.GITHUB_SHA_SHORT}}.cauldron.sefaria.org
+#          LOCAL_SELENIUM_URL: "http://localhost:4444/wd/hub"
+#          SEFARIA_TEST_PASS: ${{ secrets.SEFARIA_APP_PASS }}
+#          SEFARIA_TEST_USER: ${{ secrets.SEFARIA_APP_USER }}
+#          PYTHONPATH: "."
+#          DJANGO_SETTINGS_MODULE: sefaria.settings
+#
+#      - name: Authenticate GHA Runner to GCP
+#        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
+#        with:
+#          service_account_key: ${{ secrets.GCS_BUILD_UPLOAD_KEY }}
+#          project_id: ${{ secrets.BUILD_UPLOAD_PROJECT }}
+#        if: ${{ always() }}
+#
+#      - name: Define BUILD_RESULT_SUBDIR
+#        run: echo "BUILD_RESULT_SUBDIR=${GITHUB_SHA:0:8}" >> $GITHUB_ENV
+#        if: ${{ always() }}
+#
+#      - name: Upload Build Results
+#        run: gsutil cp /home/runner/selenium-allsuites-local.txt gs://${{secrets.GCS_BUILD_UPLOAD_BUCKET}}/${{env.BUILD_RESULT_SUBDIR}}/selenium-allsuites-local.txt
+#        if: ${{ always() }}
 
   selenium-pageloadsuite-sauce:
     name: "Selenium: Sauce"   # This name is referenced when slacking status
