Update `run_tests_on_github` to accept named test suites

diff --git a/.github/workflows/dynamic.yaml b/.github/workflows/dynamic.yaml
--- a/.github/workflows/dynamic.yaml
+++ b/.github/workflows/dynamic.yaml
@@ -52,10 +52,10 @@ jobs:
           WAIT_DURATION: "3000"
 
 
-  selenium-pageloadsuite:
+  selenium-pageloadsuite-local:
     # Start off with local firefox
     name: "Selenium Tests: PageLoad Suite on Local Linux Firefox"
-    # needs: sandbox-ready
+    needs: sandbox-ready
     runs-on: ubuntu-latest
     services: 
       selenium:
@@ -106,20 +106,16 @@ jobs:
         # run: curl localhost:5432; if [ $? -eq "52" ]; then exit 0; else exit 1; fi
         run: exitCode=$(curl localhost:5432; echo $?); if [ $exitCode -eq 52 ]; then exit 0; else exit 1; fi
 
-      - name: Define short SHA for the repo
-        id: short-sha
-        run: echo "::set-output name=commit_sha_short::$(${GITHUB_SHA:0:6})"
 
       - name: Define GITHUB_SHA_SHORT
         run: echo "GITHUB_SHA_SHORT=${GITHUB_SHA:0:6}" >> $GITHUB_ENV
 
       # END SETUP
-
       - name: Install Python Packages
         run: pip3 install -r ./requirements.txt
 
       - name: Run PageLoad Suite
-        run: python3 ./reader/browsertest/run_local_sel.py --parallel --tests PageLoadSuite
+        run: python3 ./reader/browsertest/run_local_sel.py --parallel --tests PageloadSuite
         env:
           CI_RUN: "true"
           CI_URL: https://${{env.GITHUB_SHA_SHORT}}.cauldron.sefaria.org
@@ -129,35 +125,83 @@ jobs:
           PYTHONPATH: "."
           DJANGO_SETTINGS_MODULE: sefaria.settings
 
+  selenium-pageloadsuite-sauce:
+    # Start off with local firefox
+    name: "Selenium Tests: PageLoad Suite on Local Linux Firefox"
+    needs: sandbox-ready
+    runs-on: ubuntu-latest
+    services: 
+      selenium:
+        image: selenium/standalone-firefox:3.141.59
+        ports: [ "4444:4444" ]
+        volumes: ["/dev/shm:/dev/shm"]
+    steps:
 
-      - name: Run PageLoad Suite 2
-        run: python3 ./reader/browsertest/run_local_sel.py --parallel --tests PageLoadSuite
+      # BEGIN SETUP
+      - name: Checkout Code
+        uses: actions/checkout@v2
+      - name: Set Up Python 3
+        uses: actions/setup-python@v1
+        with: 
+          python-version: '3.7'  
+
+      # Set Up Connection to Dev Mongo
+      # 1. Auth to cluster
+      # 2. Open encrypted connection
+      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
+        with:
+          service_account_key: ${{ secrets.DEV_CLOUDBUILD_SA_KEY }}
+          project_id: ${{ secrets.DEV_PROJECT }}
+
+      - name: Authenticate GHA Runner To Target Cluster
+        run: gcloud container clusters get-credentials ${{secrets.DEV_GKE_CLUSTER}} --zone ${{secrets.DEV_GKE_REGION}} --project ${{secrets.DEV_GCP_PROJECT}}
+
+      - name: Establish MongoDB Connection
+        run: kubectl port-forward svc/mongo 27017:27017 &
+      
+      - name: Await MongoDB Connection
+        run: sleep 20
+
+      - name: Confirm MongoDB Connection
+        # The following command returns a success code if mongo is available,
+        # and a failure code if it is not
+        run: curl localhost:27017
+
+      - name: Establish PostgreSQL Connection
+        run: kubectl port-forward svc/postgres 5432:5432 &
+
+      - name: Await MongoDB Connection
+        run: sleep 20
+
+      - name: Confirm PostgreSQL Connection
+        # if the PostgreSQL server is available, curl will fail with a '52' exit code
+        # if it is NOT available, it will fail with a '7' exit code
+        # run: curl localhost:5432; if [ $? -eq "52" ]; then exit 0; else exit 1; fi
+        run: exitCode=$(curl localhost:5432; echo $?); if [ $exitCode -eq 52 ]; then exit 0; else exit 1; fi
+
+      - name: Define GITHUB_SHA_SHORT
+        run: echo "GITHUB_SHA_SHORT=${GITHUB_SHA:0:6}" >> $GITHUB_ENV
+
+      # END SETUP
+      - name: Install Python Packages
+        run: pip3 install -r ./requirements.txt
+
+      - name: Run PageLoad Suite
+        run: python3 ./reader/browsertest/run_local_sel.py --parallel --tests PageloadSuite
         env:
           CI_RUN: "true"
-          CI_URL: https://${GITHUB_SHA_SHORT}.cauldron.sefaria.org
-          LOCAL_SELENIUM_URL: "http://localhost:4444/wd/hub"
+          CI_URL: https://${{env.GITHUB_SHA_SHORT}}.cauldron.sefaria.org
           SEFARIA_TEST_PASS: ${{ secrets.SEFARIA_APP_PASS }}
           SEFARIA_TEST_USER: ${{ secrets.SEFARIA_APP_USER }}
           PYTHONPATH: "."
           DJANGO_SETTINGS_MODULE: sefaria.settings
-
-      - name: Run PageLoad Suite 3
-        run: python3 ./reader/browsertest/run_local_sel.py --parallel --tests PageLoadSuite
-        env:
-          CI_RUN: "true"
-          CI_URL: https://${{steps.short-sha.outputs.commit_sha_short}}.cauldron.sefaria.org
-          LOCAL_SELENIUM_URL: "http://localhost:4444/wd/hub"
-          SEFARIA_TEST_PASS: ${{ secrets.SEFARIA_APP_PASS }}
-          SEFARIA_TEST_USER: ${{ secrets.SEFARIA_APP_USER }}
-          PYTHONPATH: "."
-          DJANGO_SETTINGS_MODULE: sefaria.settings
-
 
   sandbox-cleanup:
     name: "Clean up CI Sandbox"
     if: ${{ always() }}
     needs: 
-      - selenium-pageloadsuite
+      - selenium-pageloadsuite-local
+      - selenium-pageloadsuite-sauce
     runs-on: ubuntu-latest
     steps: 
       - name: Checkout
